### ISSUE TITLE
Full backup does not contain InfluxDB addon

### ISSUE THREAD

**Issue by bcutter** [thomasmauerer/hassio-addons#93] opened 2022-07-03 11:31 UTC
For some while ago (probably because of a HA Supervisor update? ... which happen silently) my daily full backups do not contain InfluxDB addon.

Addon version:

`5.1.0`
(issue already existed before the update so on 5.0.0)

Addon config:
```
host: xxx.xxx.xxx.xxx
share: Backups
target_dir: servername
username: username
password: password
keep_local: 7
keep_remote: '45'
trigger_time: '02:00'
trigger_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
exclude_addons: []
exclude_folders: []
workgroup: ABC
backup_name: '{type} Backup {version} {date}'
log_level: info
```

HA versions:
```
Home Assistant Core 2022.6.7

Home Assistant Supervisor 2022.05.3

Home Assistant OS 8.2

```

**How to fix this?**

Is the syntax for excluding addons/folders correct? Because when once tapping in the fields they get marked red:

![image](https://user-images.githubusercontent.com/13799156/177037565-2edab7d2-588f-4286-98c7-6fb2f5aa0c33.jpeg)

Investigations:

1) When starting the backup manually, it reliably creates a full backup. For this I use:
```
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: trigger
```
2) Log of last scheduled run (missing the InfluxDB addon again):
```
[22-07-04 02:00:52] INFO: Backup running ...
[22-07-04 02:00:53] INFO: Creating backup "Full Backup 2022.6.7 2022-07-04 02:00"
[22-07-04 02:38:30] INFO: Copying backup 5df1e633 (Samba_Backup_Full_Backup_2022_6_7_2022_07_04_02_00.tar) to share
[22-07-04 02:42:30] INFO: Deleting 1ce16c35 (Full Backup 2022.6.7 2022-06-29 02:00) local
[22-07-04 02:42:31] INFO: Deleting 48d3c422 (Full Backup 2022.6.7 2022-06-28 02:00) local
[22-07-04 02:42:32] INFO: Deleting Samba_Backup_Full_Backup_2022_3_7_2022_05_25_03_00.tar on share
[22-07-04 02:42:43] INFO: Backup finished
```

**Comment by bcutter** [comment] 2022-07-04 11:16
Added further details in "investigations" section.

Scheduled SAMBA backup simply does not reliably catch the InfluxDB addon anymore.

Nothing interesting in logs.

Only recent change was updating HA OS to v8.2.

Ideas welcome!

**Comment by bcutter** [comment] 2022-07-08 21:22
Update: After restarting...
- HA
- SAMBA backup addon
- InfluxDB addon

...the full backup is again containing the InfluxDB addon.
As this is working now for 4 intervals (days), I consider it as reliable again without knowing the reason for this issue.

**Comment by thomasmauerer** [comment] 2022-07-08 21:37
Great to hear that. It seems that the supervisor is currently a bit unstable. If the issue reoccurs, please check the supervisor logs for errors during backup creation. It should look like this:

```
22-07-08 23:19:30 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb
22-07-08 23:19:30 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_influxdb
```

**Comment by bcutter** [comment] 2022-07-10 13:31
Oh man... closed this one too early. Can we please reopen it @thomasmauerer? Looks like there's a need to track down the actual issue... 🥴

This night it happened again.

**SAMBA Backup addon log:**
```
[22-07-10 02:00:29] INFO: Backup running ...
[22-07-10 02:00:30] INFO: Creating backup "Full Backup 2022.6.7 2022-07-10 02:00"
[22-07-10 02:42:47] INFO: Copying backup fade2eaa (Samba_Backup_Full_Backup_2022_6_7_2022_07_10_02_00.tar) to share
[22-07-10 02:45:51] INFO: Deleting 00a681f5 (Full Backup 2022.6.7 2022-07-05 02:00) local
[22-07-10 02:45:52] INFO: Deleting Samba_Backup_Full_Backup_2022_4_7_2022_05_31_03_00.tar on share
[22-07-10 02:46:06] INFO: Backup finished
```

**For the supervisor logs:**
I only have the latest ones in the HA user interface. **How to get older ones?**

But those recent ones show that SAMBA backup spams the log quite heavily (only excerpt):
```
22-07-10 13:19:02 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:24:05 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:29:08 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:30:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-07-10 13:34:11 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:39:14 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:44:17 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:49:20 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:54:24 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 13:59:27 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-07-10 14:00:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-07-10 14:04:30 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
```

**Comment by bcutter** [comment] 2022-07-20 00:33
Happened again. Here's the supervisor log as requested @thomasmauerer :

```
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_samba
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_samba
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_deconz
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_deconz
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_nodered
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_nodered
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_cec_scan
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_cec_scan
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_appdaemon
22-07-20 02:00:34 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_appdaemon
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_home-panel
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_home-panel
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_motioneye
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_motioneye
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_sqlite-web
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_sqlite-web
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_letsencrypt
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_letsencrypt
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_portainer
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_portainer
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_ada
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_ada
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_ssh
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_ssh
22-07-20 02:00:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_almond
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_almond
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_configurator
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_configurator
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_grafana
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_grafana
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_logviewer
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_logviewer
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_mariadb
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_mariadb
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 15d21743_samba_backup
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 15d21743_samba_backup
22-07-20 02:00:36 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_glances
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_glances
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_ssh
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_ssh
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_check_config
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_check_config
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 6e66619d_room_assistant
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 6e66619d_room_assistant
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_aircast
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_aircast
22-07-20 02:08:42 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_unifi
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_unifi
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_duckdns
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_duckdns
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_nginx_proxy
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_nginx_proxy
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_traccar
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_traccar
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_phpmyadmin
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_phpmyadmin
22-07-20 02:08:49 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_vscode
22-07-20 02:10:52 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_vscode
```

As you can see it just skips the InfluxDB addon. There's no `Finish backup for addon a0d7b954_influxdb`. What next?

**Comment by bcutter** [comment] 2022-07-20 16:58
Please note that on addon version 5.1.1 this issue continues.

**Comment by bcutter** [comment] 2022-07-21 00:46
Another day, same story.

![image](https://user-images.githubusercontent.com/13799156/180106133-2eb37282-bf39-46ce-9f43-3da34af99e3b.png)

**Comment by thomasmauerer** [comment] 2022-07-22 10:37
> Please note that on addon version 5.1.1 this issue continues.

Because this is not an issue in Samba Backup.

I guess the root cause is directly in the InfluxDB addon, not the supervisor. Backing up databases is not a trivial task. For MariaDB for instance, the tables are locked before the backup is started. I don't know if a similar mechanism exists for InfluxDB. You could open an issue at the InfluxDB repo with the given supervisor logs.

**Comment by bcutter** [comment] 2022-07-28 21:47
I'll give it a try. Maybe I can set the log level of the supervisor to debug / maximum details somehow to get a bit more than 

`Can't write tarfile <securetar.SecureTarFile object at 0x7f7f2408b0>: [Errno 2] No such file or directory: '/data/addons/data/a0d7b954_influxdb/influxdb/data/_internal/monitor/266'`

?

**Comment by bcutter** [comment] 2022-08-18 11:37
@thomasmauerer any idea how to get more detailed information?

https://github.com/thomasmauerer/hassio-addons/issues/93#issuecomment-1198665291

**Comment by mdegat01** [comment] 2022-08-31 17:16
There hasn't really been any changes around backups for some time in supervisor. If you can pinpoint a release or a timeframe I can take a look but I really don't know what that would be.

How many backups do you keep? Are you able to pull those apart and look at the size of your influxDB addon over time? InfluxDB is a DB so it grows quite large over time. I'm wondering if its not a supervisor change at the root but rather that the size of the addon reached a threshold that started exposing issues.

I guess a few thoughts here:
1. Do you really need to backup the InfluxDB? It's so huge as you noted which is going to really complicate things. It increases both your backup and restore time massively. And its just historical data at the end of the day. To each their own but I suppose my thought process is if I plan to migrate between systems I'll take one backup of everything and then move. And if my system crashes I would rather get up and running as quickly as possible even if that means I lost history. I'll try to recover that if I can but the data is not nearly as critical as all the config and automations.

2. If you do want your historical data backed up, consider using an alternative process for InfluxDB. Taking backups of that particular addon is really just a waste of a ton of storage space. The problem is every backup of the InfluxDB addon includes all the data of the previous backup and then some new stuff. Which basically means every backup of the InfluxDB addon other then the latest is junk. If you do actually care about the historical data you would *never* want to restore any backup besides the latest for that particular addon. Perhaps instead consider setting up a process to specifically [export your InfluxDB data to files](https://stackoverflow.com/questions/27779472/export-data-from-influxdb) on a different schedule.

3. If you really really want to backup the InfluxDB addon then try stopping it before backup and starting it afterwards. I think what you're seeing is a race condition where securetar builds an iterator of all the files in a folder but by the time it gets to some of the files at the end they're gone. Because InfluxDB is still running and some of the other files were huge and took a while to process. If that works you could make a feature request to the InfluxDB addon to add `backup: cold` to its [configuration](https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options). Or if there's a better way to do something similar to the freeze option in MariaDB.

**Comment by thomasmauerer** [comment] 2023-04-29 08:54
As stated above, this issue is nothing that could be fixed here in Samba Backup. I saw that the issue reported in the InfluxDB repo got closed, so I'm closing this as well now.

**Closed by thomasmauerer** 2023-04-29 08:54 UTC

**Comment by bcutter** [comment] 2023-04-29 11:13
For the notes: It got closed there because NOBODY cared. InfluxDB addon is unmaintained. So that's not a reason ;-)

(...but this issue doesn't bother me currently so in the end it is how it is.)

**Comment by Devqon** [comment] 2024-11-29 10:29
Also for the notes:

This probably happens because InfluxDB does not support 'hot' backup, e.g. you cannot `tar` the db files while the container is running. It seems addons like MariaDB work around that by 'freezing' the tables, which will unlock handling the files for the backup.
An easy workaround would probably be to configure the InfluxDB addon to use the `cold` backup method, as documented here: https://developers.home-assistant.io/docs/add-ons/configuration

> backup - hot or cold. If cold, the supervisor turns the add-on off before taking a backup (the pre/post options are ignored when cold is used).
