### ISSUE TITLE
Invalid numeric literal

### ISSUE THREAD

**Issue by LuckyTriple7** [thomasmauerer/hassio-addons#74] opened 2022-01-03 07:00 UTC
I have Problems with external Backup to FritzBox NAS:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22-01-02 08:48:05] INFO: ---------------------------------------------------
[22-01-02 08:48:05] INFO: Host/Share: 192.168.178.1/fritz.nas
[22-01-02 08:48:05] INFO: Target directory: Lexar/HABackup
[22-01-02 08:48:05] INFO: Keep local/remote: 10/7
[22-01-02 08:48:05] INFO: Trigger time: 02:00
[22-01-02 08:48:05] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
[22-01-02 08:48:05] INFO: ---------------------------------------------------
[22-01-02 08:48:06] INFO: Samba Backup started successfully
[22-01-03 02:00:18] INFO: Backup running ...
[22-01-03 02:00:20] INFO: Creating backup "Samba Backup 2022-01-03 02:00"
parse error: Invalid numeric literal at line 1, column 5`

**parse error: Invalid numeric literal at line 1, column 5**

Host: 192.168.178.1
Share: fritz.nas
Directory: Lexar/HABackup

![image](https://user-images.githubusercontent.com/60685158/147905824-255d8013-f804-4ee6-bc73-49f112fe5e0f.png)

![image](https://user-images.githubusercontent.com/60685158/147905850-debd4e5a-e9a8-48c5-8555-a54cb60a61ec.png)

what could be the problem?

**Comment by thomasmauerer** [comment] 2022-01-03 10:14
This is a duplicate of #65 
The reason for this issue is a timeout. You need to make sure that the snapshot creation does not exceed 3 hours by either excluding some heavy addons like a DB or getting better hardware in order to speed up the snapshot creation.

The only thing I can do is write a clear error message in this case, but I cannot really solve the issue.

**Comment by LuckyTriple7** [comment] 2022-01-03 10:55
Thx Tom for the Information.
The Solution is maybe an second AddOn which transfers the Backup to an SMB Share or what ever AFTER
the Backup Process is finished ? The local backups are okay?

**Comment by thomasmauerer** [comment] 2023-04-29 07:53
I'm cleaning up some of the issues here. This is already tracked in #65 
--> closed

**Closed by thomasmauerer** 2023-04-29 07:53 UTC
