### ISSUE TITLE
Samba Backup stopped working

### ISSUE THREAD

**Issue by jamesrshaffer** [thomasmauerer/hassio-addons#112] opened 2022-10-01 18:55 UTC
Samba backup was working just fine, then in July is stopped backing up. Can't tell why. I literally de/reinstalled it and get the same result. Here's the YAML:

`host: 192.168.1.19
share: MosquitoShare
target_dir: snapshots
username: jim
password: jrs243795
keep_local: "5"
keep_remote: "10"
trigger_time: "00:23"
trigger_days:
  - Mon
  - Tue
  - Wed
  - Thu
  - Fri
  - Sat
  - Sun
exclude_addons: []
exclude_folders: []
log_level: debug
`

Here's the log. (I set the log level to debug): 

> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> cont-init: info: running /etc/cont-init.d/00-banner.sh
> 
>  Add-on: Samba Backup
>  Create backups and store them on a Samba share
>
>  Add-on version: 5.1.2
>  You are running the latest version of this add-on.
>  System: Home Assistant OS 9.0  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 2022.9.7
>  Home Assistant Supervisor: 2022.09.1
>
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> 
> cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
> cont-init: info: running /etc/cont-init.d/01-log-level.sh
> Log level is set to DEBUG
> cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> [22-09-30 20:56:31] INFO: ---------------------------------------------------
> [22-09-30 20:56:31] INFO: Host/Share: 192.168.1.19/MosquitoShare
> [22-09-30 20:56:31] INFO: Target directory: snapshots
> [22-09-30 20:56:31] INFO: Keep local/remote: 5/10
> [22-09-30 20:56:31] INFO: Trigger time: 00:23
> [22-09-30 20:56:31] INFO: Trigger days: Mon Tue Wed Thu Fri Sat Sun
> [22-09-30 20:56:31] INFO: ---------------------------------------------------
> [22-09-30 20:56:31] DEBUG: Backups local: 20
> [22-09-30 20:56:31] DEBUG: Backups remote: 20
> [22-09-30 20:56:31] DEBUG: Total backups succeeded: 451
> [22-09-30 20:56:31] DEBUG: Total backups failed: 17
> [22-09-30 20:56:31] DEBUG: Last backup: 2022-08-18 03:24
> [22-09-30 20:56:32] DEBUG: Posting sensor data to API at /core/api/states/sensor.samba_backup
> [22-09-30 20:56:32] DEBUG: API Status: 200
> [22-09-30 20:56:32] DEBUG: API Response: {"entity_id":"sensor.samba_backup","state":"IDLE","attributes":{"friendly_name":"Samba Backup","backups_local":"20","backups_remote":"20","total_backups_succeeded":"451","total_backups_failed":"17","last_backup":"2022-08-18 03:24"},"last_changed":"2022-09-30T07:23:23.191380+00:00","last_updated":"2022-09-30T07:23:23.191380+00:00","context":{"id":"01GE6MEJNQMX5YJ9V86EAAR8KG","parent_id":null,"user_id":"c505b8ebe78244ee92fe2eb1e4dbf7a3"}}
> [22-09-30 20:56:32] DEBUG: putting file samba-tmp123 as \snapshots\samba-tmp123 (0.0 kb/s) (average 0.0 kb/s)
> [22-09-30 20:56:32] INFO: Samba Backup started successfully
> [22-09-30 20:56:32] DEBUG: Starting stdin listener ...
> [22-09-30 20:56:32] DEBUG: Starting main loop ...
> [22-10-01 00:23:35] INFO: Backup running ...
> [22-10-01 00:23:35] DEBUG: Posting sensor data to API at /core/api/states/sensor.samba_backup
> [22-10-01 00:23:35] DEBUG: API Status: 200
> [22-10-01 00:23:35] DEBUG: API Response: {"entity_id":"sensor.samba_backup","state":"RUNNING","attributes":{"friendly_name":"Samba Backup","backups_local":"20","backups_remote":"20","total_backups_succeeded":"451","total_backups_failed":"17","last_backup":"2022-08-18 03:24"},"last_changed":"2022-10-01T04:23:35.408477+00:00","last_updated":"2022-10-01T04:23:35.408477+00:00","context":{"id":"01GE8WJ2QGK6B7SM8FNZNS5TM0","parent_id":null,"user_id":"c505b8ebe78244ee92fe2eb1e4dbf7a3"}}
> [22-10-01 00:23:35] INFO: Creating backup "Samba Backup 2022-10-01 00:23"
> **parse error: Invalid numeric literal at line 1, column 5**
> [22-10-01 03:23:36] DEBUG: Posting sensor data to API at /core/api/states/sensor.samba_backup
> [22-10-01 03:23:36] DEBUG: API Status: 200
> [22-10-01 03:23:36] DEBUG: API Response: {"entity_id":"sensor.samba_backup","state":"FAILED","attributes":{"friendly_name":"Samba Backup","backups_local":"21","backups_remote":"20","total_backups_succeeded":"451","total_backups_failed":"18","last_backup":"2022-08-18 03:24"},"last_changed":"2022-10-01T07:23:36.256115+00:00","last_updated":"2022-10-01T07:23:36.256115+00:00","context":{"id":"01GE96VPE091ERV0WSDRFYS4BV","parent_id":null,"user_id":"c505b8ebe78244ee92fe2eb1e4dbf7a3"}}
> [22-10-01 03:23:46] DEBUG: Posting sensor data to API at /core/api/states/sensor.samba_backup
> [22-10-01 03:23:46] DEBUG: API Status: 200
> [22-10-01 03:23:46] DEBUG: API Response: {"entity_id":"sensor.samba_backup","state":"IDLE","attributes":{"friendly_name":"Samba Backup","backups_local":"21","backups_remote":"20","total_backups_succeeded":"451","total_backups_failed":"18","last_backup":"2022-08-18 03:24"},"last_changed":"2022-10-01T07:23:46.509707+00:00","last_updated":"2022-10-01T07:23:46.509707+00:00","context":{"id":"01GE96W0EDFHRWYY35JDXFW7RN","parent_id":null,"user_id":"c505b8ebe78244ee92fe2eb1e4dbf7a3"}}
> [22-10-01 03:23:46] INFO: Backup finished

**Comment by thomasmauerer** [comment] 2022-10-21 21:46
This is a duplicate of #65 and #74. You have to make sure that the backup finishes in less than 3 hours. Please check out the mentioned issues for more details.

I'm closing this issue since it is already tracked in this project.

**Closed by thomasmauerer** 2022-10-21 21:46 UTC
