### ISSUE TITLE
null.tar error

### ISSUE THREAD

**Issue by Gerben321** [thomasmauerer/hassio-addons#32] opened 2020-12-09 16:04 UTC
Hi there, your addon worked last night, but I noticed I had no snapshot today. This was in my log. I did not change anything since it worked.

```
17:03:10] INFO: Copying snapshot null.tar to share
[17:03:10] WARNING: null.tar does not exist
[17:03:10] WARNING: Could not copy snapshot null.tar to share. Trying again ...
[17:03:15] WARNING: null.tar does not exist
[17:03:26] INFO: Backup finished
```

**Comment by thomasmauerer** [comment] 2020-12-10 07:04
Hi. That means that the snapshot creation itself failed. The creation is done by the supervisor. Is there any hint in the supervisor logs?

**Comment by buffedelic** [comment] 2020-12-19 14:24
Hi. I had the exact same issue after installing. Propaply due to initially fiddling about in the config. It probably fired several backup attempts at the same time...
After a reboot it successfully triggered and made a backup on time.

**Comment by Petro31** [comment] 2021-06-12 19:24
@thomasmauerer The issue is related to how long it takes to create the snapshot.  I decided to give this addon a shot today and that's the first thing I noticed.  A raw snapshot of my system takes 4 minutes and this addon waited about 21 seconds.

```
[15:17:21] INFO: Creating snapshot "v2021.7.0.dev20210610 Snapshot 2021-06-12 15:17"
[15:17:22] INFO: Copying snapshot null (Samba_Backup_v2021_7_0_dev20210610_Snapshot_2021_06_12_15_17.tar) to share
[15:17:22] WARNING: null.tar does not exist
[15:17:22] WARNING: Could not copy snapshot null to share. Trying again ...
[15:17:27] WARNING: null.tar does not exist
[15:17:38] INFO: Backup finished
```
I was just testing, I'll be filtering out all the addons

**Comment by gabrielmc9** [comment] 2021-07-12 12:37
I had the exact same error which occurred after I upgraded to HA OS 6.1 on an RPi4.  Restarting Samba Backup resolved the issue.

**Comment by JohannCR** [comment] 2021-07-13 07:17
Same error. It is constant, no amount of rebooting either the addon of HA fixes it for me.
I noticed it only happens for partial snapshots. Full snapshots work ok.

**Comment by golddragon007** [comment] 2021-07-13 19:11
I triggered the backup to test, and I got the same error on RPI4:
```
[21:09:52] INFO: Backup running ...
[21:09:55] INFO: Creating snapshot "Full Snapshot 2021.5.4 2021-07-13 21:09"
[21:09:56] INFO: Copying snapshot null (Samba_Backup_Full_Snapshot_2021_5_4_2021_07_13_21_09.tar) to share
[21:09:56] WARNING: null.tar does not exist
[21:09:56] WARNING: Could not copy snapshot null to share. Trying again ...
[21:10:01] WARNING: null.tar does not exist
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Also no backup was made, I can't see any backup file via superviser.

**Comment by rangulvers** [comment] 2021-08-16 19:09
Rebooting the Addon did the trick for me

**Comment by thomasmauerer** [comment] 2021-09-08 19:38
@golddragon007  Thanks for the link.
I'm closing this now as the root cause of this issue is not in this addon.

**Closed by thomasmauerer** 2021-09-08 19:38 UTC
