### ISSUE TITLE
attribute last_backup shows the timestamp of the last addon start while running a backup

### ISSUE THREAD

**Issue by nelbs** [thomasmauerer/hassio-addons#110] opened 2022-09-24 21:26 UTC
While the backup is running the attribute last_backup gives a date 8 days in the past. This issue causes some problems with a template sensor I use which checks whether the backup has been performed recently.

![image](https://user-images.githubusercontent.com/6464671/192114734-dcb5fe15-bf66-4064-8425-c4d62d89beed.png)
![image](https://user-images.githubusercontent.com/6464671/192118695-bbc2dea3-749c-447c-ac39-ceb55ac3a2f3.png)

**Comment by nelbs** [comment] 2022-10-10 22:02
On a closer look, the value is indeed not 8 days in the past but a fixed value of 15 sept.

**Comment by nelbs** [comment] 2022-10-14 08:51
> Perhaps it's the first update timestamp after the last addon start?

Did some tests and can confirm that the sensor uses the timestamp after the last addon start while running a backup.

**Comment by thomasmauerer** [comment] 2022-10-21 08:04
@bcutter Please reconsider your writing style. This is an open source project! If you need an **urgent** response or fix, do it yourself or hire somebody. I'm developing this in my freetime and do not have to provide any support at all.

That being said, back to the issue. Check the hidden .samba_backup.sensor file in your backup folder. It seems that the addon is no longer able to write to that file. Have file permissions been changed? You could also delete the file and check if the addon is able to recreate it after restarting.

**Comment by thomasmauerer** [comment] 2022-10-21 10:03
Ah ok now I got you. Yes, the issue is reproducible, I'll provide a fix.

**Comment by thomasmauerer** [comment] 2022-10-21 21:35
Fixed in v5.2.0

**Closed by thomasmauerer** 2022-10-21 21:35 UTC
