### ISSUE TITLE
Samba addon crashes if samba location is offline

### ISSUE THREAD

**Issue by abonforti** [thomasmauerer/hassio-addons#155] opened 2023-08-09 18:17 UTC
I've noticed that Samba Addon is exiting the container if the destination is unavailable. Would be possible to introduce a setting for which the addon only tries to reach out the samba destination when the cron should start?
I often shutdown my nas and periodically turn on (just before the cron schedule).

**Comment by thomasmauerer** [comment] 2023-08-28 20:58
duplicate of #148

**Closed as completed by thomasmauerer** 2023-08-28 20:58 UTC
