### ISSUE TITLE
Backup fails after one has succeeded 

### ISSUE THREAD

**Issue by stofakiller** [thomasmauerer/hassio-addons#142] opened 2023-04-15 16:20 UTC
Everything on my HA is updated and running 2023.4.4

I have noticed every time a backup is succeeded and I run the script again it fails without reason, even with logging set to debug

Stop/start or restart samba backup doesn’t help. Only a reboot of the hole HA

[23-04-15 18:04:00] INFO: Backup finished

[23-04-15 18:06:51] INFO: Creating backup "HA backup 2023-04-15 18:06"
[23-04-15 18:06:51] ERROR: Error occurred! Backup could not be created! Please try again

[23-04-15 18:10:22] INFO: Creating backup "Samba Backup 2023-04-15 18:10"
[23-04-15 18:10:22] ERROR: Error occurred! Backup could not be created! Please try again

**Comment by thomasmauerer** [comment] 2023-04-29 08:31
Duplicate of #138

**Closed by thomasmauerer** 2023-04-29 08:31 UTC
