### ISSUE TITLE
CPU + RAM Sensor "unavailable" since update

### ISSUE THREAD

**Issue by JensJott** [thomasmauerer/hassio-addons#85] opened 2022-05-16 17:20 UTC
I updated OS + Supervisor today, I don't know which update caused it:

![grafik](https://user-images.githubusercontent.com/71088451/168648105-7c2153c4-1452-43b1-9fed-f991424a8db2.png)

The plugin is running, of course.

**Comment by JensJott** [comment] 2022-05-16 18:28
More errors in log:

22-05-16 20:18:25 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:18:25 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:18:25 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:18:55 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:18:55 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:18:56 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:19:26 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:19:26 INFO (SyncWorker_9) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:19:27 INFO (SyncWorker_9) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:19:57 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:19:57 INFO (SyncWorker_8) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:19:57 INFO (SyncWorker_8) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:20:27 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:20:27 INFO (SyncWorker_9) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:20:28 INFO (SyncWorker_9) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:20:58 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:20:58 INFO (SyncWorker_8) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:20:59 INFO (SyncWorker_8) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:21:29 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:21:29 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:21:29 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0
22-05-16 20:22:00 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 15d21743_samba_backup!
22-05-16 20:22:00 INFO (SyncWorker_9) [supervisor.docker.interface] Cleaning addon_15d21743_samba_backup application
22-05-16 20:22:00 INFO (SyncWorker_9) [supervisor.docker.addon] Starting Docker add-on thomasmauerer/samba-backup-aarch64 with version 5.0.0

**Comment by thomasmauerer** [comment] 2022-07-01 17:22
The CPU and RAM info which is shown on the add-on pages is managed by the supervisor, not by add-ons themselves. So unfortunately, I cannot provide support here.

**Comment by JensJott** [comment] 2022-07-01 18:51
The plugin stopped working completely in fact, I forgot to update this report. The sensors didn't work because it crashed constantly.
I just installed 5.1.0 and it seems to be working again. Thank you!

**Comment by JensJott** [comment] 2022-07-06 18:37
You're right:

[core-ssh ~]$ nslookup jayberryjay
Server:         127.0.0.11
Address:        127.0.0.11#53

*** Can't find jayberryjay: No answer

[core-ssh ~]$ nslookup jayberryjay.fritz.box
Server:         127.0.0.11
Address:        127.0.0.11#53

Name:   jayberryjay.fritz.box
Address: 192.168.0.2

However this configuration was working before I updated to HA OS 8.

Thank you for your help! Great plugin.

**Comment by thomasmauerer** [comment] 2022-07-08 18:13
There is not an easy answer under which circumstances DNS is working from inside Home Assistant add-ons. It depends on your setup and environment. Using IP addresses is definitely more reliable.

So I assume the issue is resolved then. I'm closing this now.

**Closed by thomasmauerer** 2022-07-08 18:13 UTC
